# Uncomment this line to define a global platform for your project
# platform :ios, '6.0'

pod 'performSelector-swift'
pod 'SwiftyJSON'

link_with 'ChineseTraditionalColors', 'ChineseTraditionalColorsTests'

use_frameworks!