# Uncomment this line to define a global platform for your project
# platform :ios, '6.0'

source 'https://github.com/CocoaPods/Specs.git'

target 'ChineseTraditionalColors' do
pod 'performSelector-swift'

end

target 'ChineseTraditionalColorsTests' do

end

